import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F9FAFB' },
    scrollContent: { padding: 20, paddingBottom: 40 },
    headerContainer: { marginBottom: 30, alignItems: 'center' },
    headerTitle: { fontSize: 24, fontWeight: '800', color: '#1F2937', marginBottom: 5 },
    headerSubtitle: { fontSize: 14, color: '#6B7280' },
    avatarContainer: { alignItems: 'center', marginBottom: 25 },
    avatarWrapper: { position: 'relative' },
    avatarPlaceholder: { width: 100, height: 100, borderRadius: 50, backgroundColor: '#EFF6FF', justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#DBEAFE', borderStyle: 'dashed' },
    avatarImage: { width: 100, height: 100, borderRadius: 50, borderWidth: 2, borderColor: '#0072FF' },
    avatarText: { fontSize: 10, color: '#6B7280', marginTop: 4, fontWeight: '600' },
    editBadge: { position: 'absolute', bottom: 0, right: 0, backgroundColor: '#0072FF', width: 28, height: 28, borderRadius: 14, justifyContent: 'center', alignItems: 'center', borderWidth: 2, borderColor: '#fff' },
    formContainer: { marginBottom: 20 },
    label: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 8, marginTop: 5 },
    input: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 12, fontSize: 15, color: '#1F2937', marginBottom: 10 },
    inputError: { borderColor: '#EF4444', backgroundColor: '#FEF2F2' },
    birthdateInputButton: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        paddingHorizontal: 15,
        paddingVertical: 12,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    birthdateInputText: { fontSize: 15, color: '#1F2937' },
    birthdatePlaceholderText: { color: '#6B7280' },
    birthdatePickerWrap: {
        marginTop: -4,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 12,
        backgroundColor: '#fff',
        overflow: 'hidden',
    },
    birthdateDoneButton: {
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingHorizontal: 12,
        paddingVertical: 10,
        alignItems: 'flex-end',
    },
    birthdateDoneText: { color: '#0072FF', fontWeight: '700', fontSize: 14 },
    textArea: { height: 100 },
    errorText: { color: '#EF4444', fontSize: 12, marginTop: -5, marginBottom: 10, marginLeft: 5 },
    submitButtonContainer: { marginTop: 10, height: 50, borderRadius: 12, overflow: 'hidden', shadowColor: '#0072FF', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 5, elevation: 5 },
    gradientBtn: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    submitButtonText: { fontSize: 16, fontWeight: '700', color: '#fff' },
});