import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
    },
    sheet: {
        maxHeight: '85%',
        backgroundColor: '#F8FAFC',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    title: {
        fontSize: 16,
        fontWeight: '800',
        color: '#0F172A',
    },
    subtitle: {
        marginTop: 4,
        fontSize: 12,
        color: '#475569',
        lineHeight: 18,
    },
    closeButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E2E8F0',
    },
    content: {
        paddingHorizontal: 16,
        paddingVertical: 14,
        paddingBottom: 26,
        gap: 10,
    },
    summaryCard: {
        backgroundColor: '#E0F2FE',
        borderWidth: 1,
        borderColor: '#BAE6FD',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    summaryTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: '#075985',
    },
    summarySubtitle: {
        marginTop: 4,
        fontSize: 11,
        color: '#0369A1',
        fontWeight: '600',
    },
    sectionCard: {
        borderWidth: 1,
        borderColor: '#D8E3F0',
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 10,
        gap: 8,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    sectionHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    sectionTitle: {
        fontSize: 12,
        fontWeight: '800',
        color: '#0F172A',
    },
    sectionCount: {
        minWidth: 22,
        textAlign: 'center',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 999,
        backgroundColor: '#E2E8F0',
        color: '#334155',
        fontSize: 11,
        fontWeight: '800',
    },
    emptyWrap: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 26,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 12,
        backgroundColor: '#FFFFFF',
    },
    emptyText: {
        marginTop: 8,
        fontSize: 13,
        color: '#64748B',
        textAlign: 'center',
    },
    sectionEmptyText: {
        fontSize: 12,
        color: '#64748B',
        fontStyle: 'italic',
    },
    packageCard: {
        borderWidth: 1,
        borderColor: '#D8E3F0',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 12,
    },
    packageHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    ownerBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 999,
        backgroundColor: '#E0F2FE',
        borderWidth: 1,
        borderColor: '#BAE6FD',
        marginRight: 8,
    },
    ownerBadgeText: {
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
        color: '#0369A1',
    },
    ownerName: {
        flex: 1,
        fontSize: 12,
        color: '#334155',
        fontWeight: '600',
    },
    packageName: {
        fontSize: 15,
        fontWeight: '800',
        color: '#0F172A',
    },
    packageMeta: {
        marginTop: 4,
        fontSize: 12,
        color: '#475569',
        fontWeight: '600',
    },
    selectHintRow: {
        marginTop: 8,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    selectHintText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#1D4ED8',
    },
});
