import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    discoverSection: {
        marginTop: 0,
    },
    bannerContainer: {
        width: "100%", 
        height: 220,
        marginTop: 0, 
        marginBottom: 30,
        position: 'relative',
        justifyContent: 'flex-end'
    },
    bannerImage: {
        width: "100%", 
        height: "100%", 
        objectFit: "cover",
        position: 'absolute'
    },
    bannerTextContainer: {
        padding: 20,
        alignItems: 'center',
    },
    discoverTitle: {
        textAlign: 'center',
        fontSize: 24,
        textTransform: 'uppercase',
        letterSpacing: 2,
        fontWeight: '800',
        color: '#fff',
        textShadowColor: 'rgba(0, 0, 0, 0.5)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 5,
    },
    titleUnderline: {
        width: 60,
        height: 3,
        backgroundColor: '#00C6FF',
        marginTop: 8,
        borderRadius: 2
    },
    discoverRowWrapper: {
        width: '100%',
        height: 450,
        backgroundColor: '#000',
        position: 'relative',
    },
    scrollContainer: {
        flexDirection: 'row',
        height: '100%',
    },
    discoverItem: {
        position: 'relative',
        height: '100%',
        overflow: 'hidden',
        borderRightWidth: 0.5,
        borderColor: 'rgba(255,255,255,0.2)', 
    },
    discoverImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
        position: 'absolute',
    },
    rotatedTextContainer: {
        position: 'absolute',
        top: 0, bottom: 0, left: 0, right: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 5,
    },
    inactiveDiscoverText: {
        fontSize: 18,
        fontWeight: "800",
        color: 'rgba(255,255,255,0.85)',
        transform: [{ rotate: '-90deg' }],
        letterSpacing: 6,
        width: 450, 
        textAlign: "center",
        textShadowColor: 'rgba(0, 0, 0, 0.5)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
    activeItemContainer: {
        position: 'absolute',
        top: 0, bottom: 0, left: 0, right: 0,
        justifyContent: 'space-between',
        zIndex: 10,
    },
    titleGradientOverlay: {
        paddingTop: 40,
        paddingHorizontal: 20,
        paddingBottom: 30,
        justifyContent: 'flex-start',
    },
    activeSubtitle: {
        color: '#00C6FF',
        fontSize: 12,
        fontWeight: '700',
        letterSpacing: 1.5,
        marginBottom: 4,
    },
    activeTitle: {
        fontSize: 34,
        fontWeight: '900',
        color: '#ffffff',
        textTransform: 'uppercase',
        letterSpacing: 1,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 10,
    },
    descriptionGradientOverlay: {
        paddingTop: 50,
        paddingBottom: 30,
        paddingHorizontal: 25,
        alignItems: "center",
        justifyContent: "center"
    },
    discoverSubtext: {
        textAlign: 'center',
        fontSize: 15,
        color: '#e0e0e0',
        fontWeight: '500',
        lineHeight: 22,
    },
    AccentText: {
        color: '#00C6FF',
        fontWeight: '700',
    },
    iconCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(0, 198, 255, 0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: "#00C6FF",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
    },
    scrollHintOverlay: {
        position: 'absolute',
        top: 0,
        right: 0,
        bottom: 0,
        width: 56,
        justifyContent: 'center',
        alignItems: 'center',
    },
    scrollHintGradient: {
        ...StyleSheet.absoluteFillObject,
    },
    scrollHintIconWrap: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: 'rgba(0, 198, 255, 0.75)',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#00C6FF',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
    },
});