import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    searchWrapper: {
        width: '100%',
        position: 'relative',
        zIndex: 101,
    },
    searchBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(241, 245, 249, 0.96)',
        borderRadius: 18,
        borderWidth: 1,
        borderColor: 'rgba(226, 232, 240, 0.9)',
        paddingHorizontal: 14,
        height: 50,
        shadowColor: '#020617',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    searchBoxFocused: {
        borderColor: '#38BDF8',
        backgroundColor: 'rgba(255, 255, 255, 0.98)',
        shadowOpacity: 0.15,
    },
    input: {
        marginLeft: 10,
        flex: 1,
        height: 40,
        fontSize: 14,
        color: '#0F172A',
    },
    clearButton: {
        width: 26,
        height: 26,
        borderRadius: 13,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E2E8F0',
    },
    dropdownContainer: {
        position: 'absolute',
        top: 56,
        left: 0,
        right: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.98)',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        maxHeight: 340,
        overflow: 'hidden',
        shadowColor: '#020617',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.14,
        shadowRadius: 14,
        elevation: 12,
        zIndex: 102,
    },
    recentContainer: {
        paddingHorizontal: 14,
        paddingTop: 12,
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    recentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    recentTitle: {
        color: '#334155',
        fontWeight: '700',
        fontSize: 13,
    },
    clearRecentText: {
        color: '#0284C7',
        fontSize: 12,
        fontWeight: '600',
    },
    recentItemsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    recentChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: '#F8FAFC',
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    recentChipText: {
        color: '#334155',
        fontSize: 12,
        fontWeight: '500',
    },
    stateContainer: {
        paddingVertical: 18,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    stateTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#1E293B',
    },
    stateSubtitle: {
        fontSize: 12,
        color: '#64748B',
        textAlign: 'center',
    },
    resultsScroll: {
        maxHeight: 320,
    },
    resultsContent: {
        paddingBottom: 8,
    },
    sectionBlock: {
        paddingTop: 8,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 12,
        paddingBottom: 8,
        paddingTop: 4,
    },
    sectionIconBadge: {
        width: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 12,
        color: '#475569',
        fontWeight: '700',
        flex: 1,
    },
    sectionCount: {
        fontSize: 11,
        color: '#64748B',
        fontWeight: '600',
    },
    resultItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 9,
        borderTopWidth: 1,
        borderTopColor: '#F8FAFC',
    },
    resultItemActive: {
        backgroundColor: '#EFF6FF',
    },
    resultImage: {
        width: 40,
        height: 40,
        borderRadius: 12,
        marginRight: 10,
        backgroundColor: '#E2E8F0',
    },
    resultTextWrap: {
        flex: 1,
        marginRight: 8,
    },
    resultTitle: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '700',
    },
    resultSubtitle: {
        marginTop: 2,
        fontSize: 12,
        color: '#64748B',
    },
    resultHighlight: {
        color: '#0284C7',
    },
    resultHighlightSubtle: {
        color: '#0369A1',
        fontWeight: '700',
    },
});
