import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F5F7FA' },
    header: { position: 'relative', height: 120, justifyContent: 'center' },
    headerImage: { width: '100%', height: '100%', resizeMode: 'cover', borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    overlay: { ...StyleSheet.absoluteFillObject, borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    headerTitle: { position: 'absolute', bottom: 15, left: 20, color: '#fff', fontSize: 18, fontWeight: '700', letterSpacing: 1 },
    tierBadge: { position: 'absolute', top: 35, right: 20, backgroundColor: 'rgba(255,255,255,0.2)', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.4)' },
    tierBadgeText: { color: '#fff', fontSize: 10, fontWeight: '700', marginLeft: 6 },
    mainContent: { flexDirection: "column", gap: 15, paddingBottom: 40 },
    statusToggleContainer: { width: '90%', alignSelf: 'center', backgroundColor: '#fff', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderRadius: 16, marginTop: 15, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 4, elevation: 3, borderWidth: 1, borderColor: '#f0f0f0' },
    statusTextContainer: { flex: 1 },
    readyPromptText: { fontSize: 12, color: '#8B98A8', fontWeight: '600', marginBottom: 4, textTransform: 'uppercase' },
    statusRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 2, gap: 6 },
    statusDot: { width: 8, height: 8, borderRadius: 4 },
    statusLabel: { fontSize: 18, fontWeight: '800' },
    statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', paddingHorizontal: 15, gap: 10, marginTop: 5 },
    statCard: { backgroundColor: '#253347', borderRadius: 12, padding: 12, width: '48%', height: 100, justifyContent: 'space-between', shadowColor: '#0072FF', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.2, shadowRadius: 4, elevation: 4 },
    statHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
    statIconBg: { width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(255,255,255,0.1)', justifyContent: 'center', alignItems: 'center' },
    statValue: { fontSize: 30, fontWeight: '700', color: '#fff' },
    statLabel: { fontSize: 13, color: '#B0B8C4', fontWeight: '600' },
    statSubtext: { fontSize: 11, color: 'rgba(255,255,255,0.4)', marginTop: 2 },
    bookingsSection: { padding: 15, marginTop: 0 },
    sectionTitle: { fontSize: 14, fontWeight: '700', color: '#253347', letterSpacing: 0.5, marginBottom: 15, marginTop: 5 },
    tripsSectionHeader: { marginTop: 16, marginBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
    tripsSectionSubtext: { fontSize: 12, color: '#64748B', fontWeight: '500' },
    viewAllTripsBtn: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 6,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    viewAllTripsBtnText: { fontSize: 12, color: '#111827', fontWeight: '700' },
    tripFilterRow: { paddingBottom: 8, paddingRight: 8 },
    tripFilterRowWrap: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 8, gap: 8 },
    tripFilterChip: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        backgroundColor: '#FFFFFF',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 7,
        marginRight: 0,
    },
    tripFilterChipActive: { borderColor: '#111827', backgroundColor: '#111827' },
    tripFilterChipText: { color: '#4B5563', fontWeight: '600', fontSize: 12 },
    tripFilterChipTextActive: { color: '#FFFFFF', fontWeight: '700' },
    tripCardsRow: { paddingRight: 8 },
    tripCardsColumn: { gap: 10 },
    sectionHelpText: { fontSize: 12, color: '#64748B', marginTop: -8, marginBottom: 14, fontWeight: '500' },
    stepCard: { backgroundColor: '#fff', borderRadius: 16, padding: 18, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 6, elevation: 4, borderWidth: 1, borderColor: '#F0F0F0', position: 'relative', overflow: 'hidden' },
    stepCardActive: { backgroundColor: '#fff', borderColor: '#0072FF', borderWidth: 2, shadowColor: '#0072FF', shadowOpacity: 0.15 },
    stepCardDone: { borderColor: '#00C853', backgroundColor: '#F9FFF9' },
    startBadge: { position: 'absolute', top: 0, right: 0, backgroundColor: '#0072FF', paddingHorizontal: 12, paddingVertical: 4, borderBottomLeftRadius: 12 },
    startBadgeText: { color: '#fff', fontSize: 10, fontWeight: '800', letterSpacing: 0.5 },
    doneEditableBadge: { position: 'absolute', top: 0, right: 0, backgroundColor: '#00C853', paddingHorizontal: 10, paddingVertical: 4, borderBottomLeftRadius: 12 },
    doneEditableBadgeText: { color: '#fff', fontSize: 9, fontWeight: '800', letterSpacing: 0.4 },
    stepRow: { flexDirection: 'row', alignItems: 'center' },
    stepNumberContainer: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#F3F4F6', justifyContent: 'center', alignItems: 'center', marginRight: 15, borderWidth: 1, borderColor: '#E5E7EB' },
    stepNumberContainerActive: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#0072FF', justifyContent: 'center', alignItems: 'center', marginRight: 15 },
    stepNumberContainerDone: { backgroundColor: '#00C853', borderColor: '#00C853' },
    stepNumber: { fontSize: 14, fontWeight: '700', color: '#9CA3AF' },
    stepNumberActive: { fontSize: 14, fontWeight: '700', color: '#fff' },
    stepContent: { flex: 1 },
    stepTitle: { fontSize: 16, fontWeight: '600', color: '#4B5563', marginBottom: 2 },
    stepTitleActive: { fontSize: 16, fontWeight: '800', color: '#0072FF', marginBottom: 2 },
    stepTitleDone: { color: '#2E7D32', fontWeight: '800' },
    stepDesc: { fontSize: 12, color: '#6B7280' },
    stepHint: { marginTop: 5, fontSize: 11, color: '#94A3B8', fontWeight: '600' },
    stepHintActive: { color: '#0072FF' },
    stepHintDone: { color: '#16A34A' },
    chevronContainer: { paddingLeft: 10, justifyContent: 'center' },
    chevronContainerActive: { paddingLeft: 10, justifyContent: 'center', backgroundColor: '#F0F9FF', width: 36, height: 36, borderRadius: 18, alignItems: 'center' },
    chevronContainerDone: { backgroundColor: '#E8F5E9', width: 36, height: 36, borderRadius: 18, alignItems: 'center' },
    connectorContainer: { paddingLeft: 34, height: 16, justifyContent: 'center' },
    dottedLine: { width: 2, height: '100%', borderStyle: 'dotted', borderWidth: 1, borderColor: '#D1D5DB', borderRadius: 1 },
    emptyState: { alignItems: 'center', justifyContent: 'center', padding: 30, backgroundColor: '#fff', borderRadius: 16, borderStyle: 'dashed', borderWidth: 1, borderColor: '#B0B8C4' },
    emptyStateLight: { alignItems: 'center', justifyContent: 'center', padding: 24, backgroundColor: '#fff', borderRadius: 16, borderStyle: 'dashed', borderWidth: 1, borderColor: '#D1D5DB' },
    emptyStateText: { marginTop: 10, color: '#B0B8C4', fontSize: 14 },
    bookingCard: { backgroundColor: '#253347', borderRadius: 20, padding: 20, marginBottom: 16, shadowColor: '#253347', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.3, shadowRadius: 12, elevation: 8, borderWidth: 1, borderColor: 'rgba(255,255,255,0.05)' },
    bookingCardWhite: {
        width: '100%',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 14,
        marginRight: 0,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOpacity: 0.06,
        shadowRadius: 6,
        elevation: 2,
    },
    bookingCardWhiteModal: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 14,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15, paddingBottom: 15, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.08)' },
    cardHeaderWhite: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10, paddingBottom: 10, borderBottomWidth: 1, borderBottomColor: '#F1F5F9', gap: 8 },
    userInfo: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1, marginRight: 8 },
    avatarPlaceholder: { width: 44, height: 44, borderRadius: 22, backgroundColor: 'rgba(255,255,255,0.1)', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.2)' },
    avatarLetter: { color: '#fff', fontSize: 18, fontWeight: '800' },
    avatarPlaceholderWhite: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#EEF2FF', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
    avatarLetterWhite: { color: '#334155', fontSize: 16, fontWeight: '800' },
    touristName: { fontSize: 16, fontWeight: '700', color: '#fff', letterSpacing: 0.3 },
    touristNameWhite: { fontSize: 15, fontWeight: '700', color: '#0F172A', letterSpacing: 0.2, flexShrink: 1 },
    touristRole: { fontSize: 12, color: '#B0B8C4', fontWeight: '500' },
    touristRoleWhite: { fontSize: 12, color: '#64748B', fontWeight: '500' },
    statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
    statusBadgeTight: { flexShrink: 1, maxWidth: '42%' },
    statusText: { fontSize: 11, fontWeight: '700' },
    cardBody: { backgroundColor: 'rgba(0,0,0,0.2)', borderRadius: 12, padding: 12, marginBottom: 15 },
    cardBodyLight: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#EEF2F7' },
    dateContainer: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    dateItem: { alignItems: 'center', flex: 1 },
    dateDivider: { width: 1, height: 30, backgroundColor: 'rgba(255,255,255,0.1)' },
    dateLabel: { color: '#8B98A8', fontSize: 11, marginBottom: 4, textTransform: 'uppercase', fontWeight: '600' },
    dateValue: { color: '#fff', fontSize: 14, fontWeight: '700' },
    dateDividerLight: { width: 1, height: 30, backgroundColor: '#E5E7EB' },
    dateLabelLight: { color: '#64748B', fontSize: 11, marginBottom: 4, textTransform: 'uppercase', fontWeight: '600' },
    dateValueLight: { color: '#0F172A', fontSize: 13, fontWeight: '700' },
    messageBtn: { width: '100%', height: 44, backgroundColor: 'rgba(255,255,255,0.1)', borderRadius: 12, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: 'rgba(255,255,255,0.15)' },
    messageBtnText: { color: '#fff', fontWeight: '600', fontSize: 14 },
    messageBtnLight: { width: '100%', height: 40, backgroundColor: '#F3F4F6', borderRadius: 10, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB' },
    messageBtnTextLight: { color: '#0F172A', fontWeight: '700', fontSize: 13 },
    moreTripsHint: {
        marginTop: 10,
        alignSelf: 'center',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    moreTripsHintText: { fontSize: 12, color: '#374151', fontWeight: '600' },
    toastContainer: { position: 'absolute', bottom: 40, left: 20, right: 20, borderRadius: 12, padding: 16, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 10, zIndex: 1000 },
    toastSuccess: { backgroundColor: '#00c853' },
    toastText: { color: '#fff', fontSize: 14, fontWeight: '600', marginLeft: 12 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
    modalContent: { width: '90%', backgroundColor: '#fff', borderRadius: 24, padding: 24, maxHeight: '80%', elevation: 10 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    modalTitle: { fontSize: 20, fontWeight: '800', color: '#253347' },

    // MODAL PLAN STYLES
    planCard: {
        backgroundColor: '#F8FAFC',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#E2E8F0',
    },
    premiumCard: {
        backgroundColor: '#FFF',
        borderColor: '#FFAB00',
        borderWidth: 1,
        shadowColor: '#FFAB00',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    activePlanBorder: {
        borderColor: '#00C853',
        borderWidth: 2,
        backgroundColor: '#F0FDF4',
    },
    planHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    planName: {
        fontSize: 16,
        fontWeight: '800',
        color: '#1E293B',
    },
    planCost: {
        fontSize: 13,
        color: '#64748B',
        fontWeight: '500',
        marginTop: 2,
    },
    currentBadge: {
        backgroundColor: '#94A3B8',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    currentBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '800',
    },
    bestValueBadge: {
        backgroundColor: '#FFAB00',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    bestValueText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '800',
    },
    planFeatures: {
        gap: 8,
    },
    featureRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    featureText: {
        fontSize: 13,
        color: '#475569',
        fontWeight: '500',
    },
    upgradeBtnModal: {
        marginTop: 16,
        borderRadius: 12,
        overflow: 'hidden',
    },
    gradientBtn: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 12,
        gap: 8,
    },
    upgradeBtnText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 14,
        letterSpacing: 0.5,
    },
});
