import { StyleSheet, Dimensions } from "react-native";
const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F9FAFB' },
    header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 15, backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
    headerTitleText: { fontSize: 18, fontWeight: '700', color: '#1F2937' },
    progressContainer: { backgroundColor: '#fff', paddingVertical: 20, marginBottom: 10 },
    progressInner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', width: '100%' },
    stepDot: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#F3F4F6', justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB', zIndex: 2 },
    stepDotActive: { backgroundColor: '#0072FF', borderColor: '#0072FF', elevation: 4, shadowColor: '#0072FF', shadowOpacity: 0.3 },
    stepNumber: { fontSize: 14, fontWeight: '700', color: '#9CA3AF' },
    stepNumberActive: { color: '#fff' },
    stepLine: { width: 60, height: 3, backgroundColor: '#E5E7EB', marginHorizontal: 4, borderRadius: 2 },
    stepLineActive: { backgroundColor: '#0072FF' },
    stepContainer: { padding: 20 },
    stepTitle: { fontSize: 24, fontWeight: '800', color: '#1F2937', marginBottom: 5 },
    stepSubtitle: { fontSize: 14, color: '#6B7280', marginBottom: 25 },
    row: { flexDirection: 'row', alignItems: 'center' },
    label: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 8, marginTop: 15 },
    labelSmall: { fontSize: 12, fontWeight: '600', color: '#6B7280', marginBottom: 5 },
    input: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, paddingHorizontal: 15, paddingVertical: 12, fontSize: 15, color: '#1F2937' },
    dropdownSelector: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 12, padding: 15 },
    dropdownTextPlaceholder: { color: '#9CA3AF', fontSize: 15 },
    dropdownTextSelected: { color: '#1F2937', fontSize: 15, fontWeight: '600' },
    gridContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
    gridItemCard: { width: (width - 50) / 2, backgroundColor: '#fff', borderRadius: 12, padding: 8, borderWidth: 1, borderColor: '#E5E7EB' },
    imageUploadSmall: { height: 100, backgroundColor: '#F3F4F6', borderRadius: 8, justifyContent: 'center', alignItems: 'center', overflow: 'hidden', marginBottom: 8 },
    uploadedImage: { width: '100%', height: '100%' },
    removeIcon: { position: 'absolute', top: 5, right: 5, backgroundColor: 'rgba(0,0,0,0.5)', padding: 4, borderRadius: 10 },
    cardInput: { fontSize: 12, textAlign: 'center', padding: 4, backgroundColor: '#F9FAFB', borderRadius: 4, color: '#1F2937' },
    addStopButton: { width: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 15, marginTop: 10, borderStyle: 'dashed', borderWidth: 1, borderColor: '#0072FF', borderRadius: 12, backgroundColor: '#EFF6FF' },
    addStopText: { color: '#0072FF', fontWeight: '600', marginLeft: 8 },
    pricingCard: { backgroundColor: '#fff', padding: 15, borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB' },
    priceInputRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9FAFB', borderRadius: 8, paddingHorizontal: 10 },
    currency: { fontSize: 16, fontWeight: '700', color: '#9CA3AF', marginRight: 5 },
    priceInput: { flex: 1, paddingVertical: 10, fontSize: 16, fontWeight: '600', color: '#1F2937' },
    
    // Day Tabs Styling
    dayTab: { paddingHorizontal: 20, paddingVertical: 10, borderRadius: 20, backgroundColor: '#F3F4F6', marginRight: 10, borderWidth: 1, borderColor: '#E5E7EB' },
    dayTabActive: { backgroundColor: '#EFF6FF', borderColor: '#0072FF' },
    dayTabText: { fontSize: 14, fontWeight: '600', color: '#6B7280' },
    dayTabTextActive: { color: '#0072FF' },

    builderContainer: { backgroundColor: '#fff', padding: 15, borderRadius: 16, borderWidth: 1, borderColor: '#E5E7EB', marginTop: 5 },
    pickerTrigger: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 15, paddingVertical: 12, marginVertical: 12, backgroundColor: '#fff' },
    activityModalContent: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40, width: '100%' },
    activityModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15, paddingBottom: 15, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
    activityModalTitle: { fontSize: 18, fontWeight: '800', color: '#1F2937' },
    activitySectionTitle: { fontSize: 13, fontWeight: '700', color: '#9CA3AF', marginBottom: 8, letterSpacing: 1 },
    activityOption: { paddingVertical: 14, paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: '#F9FAFB' },
    activityOptionText: { fontSize: 16, color: '#1F2937', fontWeight: '500' },
    activityEmptyText: { color: '#9CA3AF', fontStyle: 'italic', paddingHorizontal: 10, marginVertical: 10 },
    addTimeBtn: { backgroundColor: '#0072FF', padding: 12, borderRadius: 8, alignItems: 'center', marginBottom: 15 },
    addTimeBtnText: { color: '#fff', fontWeight: '700' },
    timelineList: { marginTop: 5 },
    emptyTimelineText: { textAlign: 'center', color: '#9CA3AF', fontSize: 13, fontStyle: 'italic' },
    timelineItem: { flexDirection: 'row', marginBottom: 12 },
    timelineLeft: { width: 60, alignItems: 'center', marginRight: 10 },
    timeText: { fontSize: 11, fontWeight: '700', color: '#4B5563' },
    dotLine: { width: 1, flex: 1, backgroundColor: '#D1D5DB', marginVertical: 2 },
    timelineContent: { flex: 1, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#F3F4F6', padding: 10, borderRadius: 8 },
    activityName: { fontSize: 13, fontWeight: '600', color: '#1F2937' },
    footer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#F3F4F6', padding: 20, flexDirection: 'row', gap: 15, elevation: 10 },
    secondaryButton: { paddingHorizontal: 20, justifyContent: 'center', alignItems: 'center', backgroundColor: '#F3F4F6', borderRadius: 12, height: 50 },
    secondaryButtonText: { fontSize: 16, fontWeight: '600', color: '#4B5563' },
    primaryButton: { flex: 1, height: 50, borderRadius: 12, overflow: 'hidden' },
    gradientBtn: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    primaryButtonText: { fontSize: 16, fontWeight: '700', color: '#fff' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, maxHeight: '70%' },
    modalTitle: { fontSize: 18, fontWeight: '700', marginBottom: 15, textAlign: 'center' },
    modalItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
    modalItemText: { fontSize: 16, fontWeight: '600', color: '#1F2937' },
    modalItemSub: { fontSize: 12, color: '#6B7280' },
    modalClose: { marginTop: 15, alignItems: 'center', padding: 10 },
    modalCloseText: { color: '#FF3B30', fontSize: 16, fontWeight: '600' },
    categoryBadge: { backgroundColor: '#EFF6FF', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, borderWidth: 1, borderColor: '#BFDBFE' },
    categoryBadgeText: { fontSize: 10, color: '#1D4ED8', fontWeight: '600', textTransform: 'uppercase' },
    timePickerButton: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#E5E7EB', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12 },
    timePickerText: { fontSize: 14, color: '#1F2937' },
    toastContainer: { position: 'absolute', bottom: 80, left: 20, right: 20, borderRadius: 12, padding: 16, flexDirection: 'row', alignItems: 'center', shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 10, zIndex: 1000 },
    toastSuccess: { backgroundColor: '#00c853' },
    toastError: { backgroundColor: '#ff5252' },
    toastText: { color: '#fff', fontSize: 14, fontWeight: '600', marginLeft: 12 },
});
