import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    fullContainer: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    header: {
        position: 'relative',
        height: 120,
        justifyContent: 'center',
        marginBottom: 20,
    },
    headerImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
    },
    // --- ADDED BACK BUTTON STYLE ---
    backButton: { 
        position: 'absolute', 
        top: 20, 
        left: 20, 
        padding: 5, 
        zIndex: 10 
    },
    headerTitle: {
        position: 'absolute',
        bottom: 15,
        left: 20,
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        letterSpacing: 1,
    },
    container: { flex: 1 },
    headerSection: {
        marginBottom: 36,
        alignItems: 'center',
    },
    mainHeader: {
        fontSize: 32,
        fontWeight: '800',
        color: '#1a1a1a',
        marginBottom: 8,
        textAlign: 'center',
    },
    placeName: {
        fontSize: 24,
        fontWeight: '700',
        color: '#0066ff',
        marginBottom: 12,
        textAlign: 'center',
    },
    subtext: {
        fontSize: 14,
        color: '#999',
        fontWeight: '500',
        textAlign: 'center',
    },
    cardsContainer: {
        width: '100%',
        marginBottom: 28,
        paddingHorizontal: 20
    },
    card: {
        borderRadius: 20,
        paddingHorizontal: 20,
        paddingVertical: 0,
        marginBottom: 18,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 5,
    },
    cardSelected: { elevation: 10 },
    accentBar: {
        height: 4,
        marginHorizontal: -20,
        marginBottom: 16,
    },
    topSection: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 18,
        marginTop: 20,
        gap: 16,
    },
    iconBox: {
        width: 56,
        height: 56,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
    },
    icon: { fontSize: 32 },
    cardTitle: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1a1a1a',
        marginBottom: 4,
    },
    cardDescription: {
        fontSize: 13,
        color: '#777',
        fontWeight: '500',
        lineHeight: 18,
    },
    featuresList: { marginBottom: 20 },
    featureItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        gap: 12,
    },
    featureCheck: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 1.5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkmark: {
        fontSize: 14,
        fontWeight: '800',
    },
    featureText: {
        fontSize: 13,
        color: '#555',
        flex: 1,
    },
    buttonContainer: {
        marginHorizontal: -20,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
        overflow: 'hidden',
    },
    button: { paddingVertical: 14, alignItems: 'center' },
    buttonText: {
        color: '#ffffff',
        fontSize: 15,
        fontWeight: '800',
    },
    comparisonBox: {
        backgroundColor: '#f8fafb',
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#e8ecf1',
        marginBottom: 20,
    },
    comparisonRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    comparisonItem: { alignItems: 'center', flex: 1 },
    compLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#999',
        marginBottom: 12,
    },
    compValue: { fontSize: 13, fontWeight: '600', marginBottom: 6 },
    trustBadge: {
        alignItems: 'center',
        paddingVertical: 16,
        marginBottom: 20,
    },
    trustIcon: { fontSize: 24, marginBottom: 8 },
    trustText: {
        fontSize: 13,
        color: '#999',
        fontWeight: '500',
    },
});
