import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    mainContainer: { flex: 1, backgroundColor: '#f8f9fa' },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: { position: 'relative', height: 120, justifyContent: 'center', marginBottom: 20 },
    headerImage: { width: '100%', height: '100%', borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    overlay: { ...StyleSheet.absoluteFillObject, borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    headerContent: { position: 'absolute', bottom: 15, left: 20 },
    headerTitle: { color: '#fff', fontSize: 22, fontWeight: '800' },
    headerSubtitle: { color: '#e0e0e0', fontSize: 13 },
    topControlsContainer: {
        marginHorizontal: 16,
        marginBottom: 16,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 14,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        shadowColor: '#0F172A',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    tabSwitcher: { flexDirection: 'row', backgroundColor: '#EEF2FF', borderRadius: 12, padding: 4, marginBottom: 12 },
    tabButton: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 10, borderRadius: 10 },
    tabButtonActive: { backgroundColor: '#0EA5E9' },
    tabButtonActiveClient: { backgroundColor: '#F97316' },
    tabButtonText: { fontSize: 12, fontWeight: '800', color: '#475569' },
    tabButtonTextActive: { color: '#FFFFFF' },
    tabBadgeDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#EF4444',
        marginLeft: 6,
        marginTop: -6,
    },
    filterLabel: { fontSize: 11, fontWeight: '800', color: '#475569', marginBottom: 8, marginTop: 4, textTransform: 'uppercase', letterSpacing: 0.6 },
    filterRow: { paddingBottom: 4, paddingRight: 8 },
    filterRowWrap: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 2 },
    filterChip: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#F8FAFC',
        marginRight: 8,
        marginBottom: 8,
    },
    filterChipActive: { backgroundColor: '#E0F2FE', borderColor: '#0EA5E9' },
    filterChipText: { fontSize: 12, fontWeight: '600', color: '#334155' },
    filterChipTextActive: { color: '#0369A1', fontWeight: '800' },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        paddingHorizontal: 10,
        marginTop: 2,
        marginBottom: 6,
    },
    searchIcon: { marginRight: 6 },
    searchInput: {
        flex: 1,
        fontSize: 13,
        color: '#0F172A',
        paddingVertical: 10,
    },
    searchClearButton: { paddingLeft: 8, paddingVertical: 4 },
    sectionSummaryText: { fontSize: 12, color: '#0F172A', fontWeight: '600', marginTop: 4 },
    sortHintText: { fontSize: 11, color: '#64748B', fontWeight: '600', marginTop: 4 },
    listContainer: { paddingBottom: 40 },
    listFooterLoader: { paddingVertical: 18, alignItems: 'center' },
    groupContainer: { marginBottom: 10 },
    groupHeaderCard: {
        marginHorizontal: 16,
        borderRadius: 18,
        borderWidth: 1,
        borderColor: '#E7E5E4',
        backgroundColor: '#FFFBF5',
        padding: 10,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 10,
        elevation: 3,
    },
    groupImageWrap: {
        height: 128,
        borderRadius: 14,
        overflow: 'hidden',
        marginBottom: 10,
        backgroundColor: '#E7E5E4',
    },
    groupImage: {
        width: '100%',
        height: '100%',
    },
    groupImageFallback: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F5F5F4',
    },
    groupImageOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    groupImageBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'rgba(28,25,23,0.72)',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 5,
    },
    groupImageBadgeText: {
        color: '#F5F5F4',
        fontSize: 11,
        fontWeight: '700',
    },
    groupHeaderTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    groupTitleWrap: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 8 },
    groupTitle: { fontSize: 17, fontWeight: '800', color: '#0F172A', flexShrink: 1 },
    groupMetaRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8, flexWrap: 'wrap', gap: 8 },
    groupMetaTextStrong: { color: '#7C2D12', fontSize: 12, fontWeight: '800', width: '100%' },
    groupMetaText: { color: '#57534E', fontSize: 12, fontWeight: '600' },
    groupProceedButton: {
        marginTop: 10,
        borderRadius: 10,
        backgroundColor: '#2563EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 12,
        paddingVertical: 10,
        gap: 8,
    },
    groupProceedButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '800' },
    expandButton: {
        marginTop: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E7E5E4',
        backgroundColor: '#FFF7ED',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    expandButtonText: { fontSize: 12, fontWeight: '700', color: '#92400E' },
    groupBookingsWrap: { marginTop: 10 },
    cardContainer: { paddingHorizontal: 16, marginBottom: 16 },
    bookingCard: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 16, shadowColor: '#000', shadowOpacity: 0.05, elevation: 3, overflow: 'hidden' },
    statusStrip: { width: 6, height: '100%' },
    cardContent: { flex: 1, padding: 16 },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
    roleTag: { alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, marginBottom: 4 },
    roleTagText: { fontSize: 10, fontWeight: '800' },
    cardTitle: { fontSize: 16, fontWeight: '700', color: '#1F2937' },
    cardType: { fontSize: 12, color: '#6B7280' },
    statusBadge: { flexDirection: 'row', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, alignItems: 'center', height: 26 },
    acceptedBadge: { backgroundColor: '#DCFCE7' }, 
    acceptedText: { color: '#166534', fontSize: 11, fontWeight: '700' },
    pendingBadge: { backgroundColor: '#FEF9C3' }, 
    pendingText: { color: '#854D0E', fontSize: 11, fontWeight: '700' },
    refundedBadge: { backgroundColor: '#CCFBF1' },
    refundedText: { color: '#0F766E', fontSize: 11, fontWeight: '700' },
    declinedBadge: { backgroundColor: '#FEE2E2' }, 
    declinedText: { color: '#991B1B', fontSize: 11, fontWeight: '700' },
    defaultBadge: { backgroundColor: '#F3F4F6' },
    defaultText: { color: '#4B5563', fontSize: 11 },
    divider: { height: 1, backgroundColor: '#F3F4F6', marginVertical: 10 },
    detailsContainer: { gap: 6 },
    detailRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    iconWidth: { width: 16, textAlign: 'center' },
    detailText: { fontSize: 13, color: '#4B5563' },
    
    financialBox: { backgroundColor: '#F0FDF4', borderRadius: 8, padding: 12, marginTop: 12, borderWidth: 1, borderColor: '#BBF7D0' },
    financialBoxTourist: { backgroundColor: '#EFF6FF', borderRadius: 8, padding: 12, marginTop: 12, borderWidth: 1, borderColor: '#BFDBFE' },
    finHeader: { fontSize: 10, fontWeight: '800', color: '#15803D', letterSpacing: 0.5, textTransform:'uppercase' },
    finHeaderTourist: { fontSize: 10, fontWeight: '800', color: '#1D4ED8', letterSpacing: 0.5, textTransform:'uppercase' },
    finRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 4 },
    finLabel: { fontSize: 12, color: '#374151' },
    finValue: { fontSize: 12, fontWeight: '600', color: '#111827' },
    finSubRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3, paddingLeft: 20 },
    finSubLabel: { flex: 1, marginRight: 8, fontSize: 11, color: '#64748B' },
    finSubValue: { fontSize: 11, fontWeight: '600', color: '#334155' },
    finDivider: { height: 1, backgroundColor: '#DCFCE7', marginVertical: 6 },
    
    cardFooter: { marginTop: 16, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-start', gap: 8 },
    proceedButton: { flexDirection:'row', alignItems:'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#2563EB', borderRadius: 8, shadowColor: '#2563EB', shadowOpacity: 0.3, elevation: 3, flexShrink: 1 },
    proceedButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    cancelButton: { paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#FEF2F2', borderRadius: 8, borderWidth: 1, borderColor: '#FECACA', flexShrink: 1 },
    cancelButtonText: { color: '#DC2626', fontSize: 12, fontWeight: '700' },
    paidButton: { flexDirection:'row', alignItems:'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#22C55E', borderRadius: 8, shadowColor: "#22C55E", shadowOpacity: 0.3, elevation: 3, flexShrink: 1 },
    paidButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    messageButton: { flexDirection:'row', alignItems:'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#0EA5E9', borderRadius: 8, shadowColor: '#0EA5E9', shadowOpacity: 0.3, elevation: 3, flexShrink: 1 },
    messageButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    refundButton: { flexDirection:'row', alignItems:'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#0F766E', borderRadius: 8, shadowColor: '#0F766E', shadowOpacity: 0.3, elevation: 3, flexShrink: 1 },
    refundButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    clientRefundStatePill: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 8, backgroundColor: '#DBEAFE', borderRadius: 8, borderWidth: 1, borderColor: '#BFDBFE', flexShrink: 1 },
    clientRefundStateText: { color: '#1D4ED8', fontSize: 12, fontWeight: '700' },
    reviewButton: { flexDirection:'row', alignItems:'center', paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#F59E0B', borderRadius: 8, shadowColor: "#F59E0B", shadowOpacity: 0.3, elevation: 3, flexShrink: 1 },
    reviewButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
    refundPolicyText: { marginBottom: 10, color: '#0F766E', fontSize: 11, fontWeight: '700' },
    refundPolicyTextWarning: { color: '#B45309' },
    emptyContainer: { alignItems: 'center', marginTop: 60 },
    emptyText: { fontSize: 15, fontWeight: '700', color: '#374151', marginTop: 10, textAlign: 'center', marginHorizontal: 10 },
    destinationModalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.35)',
        justifyContent: 'flex-end',
    },
    destinationModalCard: {
        backgroundColor: '#F8FAFC',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '88%',
        minHeight: '55%',
        paddingTop: 8,
        paddingBottom: 12,
    },
    destinationModalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        paddingHorizontal: 16,
        paddingBottom: 12,
        marginBottom: 6,
    },
    destinationModalTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#0F172A',
    },
    destinationModalSubtitle: {
        fontSize: 12,
        color: '#475569',
        marginTop: 4,
        fontWeight: '600',
    },
    destinationCloseButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E2E8F0',
        marginLeft: 12,
    },
    destinationModalList: { paddingTop: 8, paddingBottom: 22 },
    destinationModalFooterLoader: { paddingVertical: 12 },
    destinationModalFooterHint: { paddingVertical: 8, alignItems: 'center' },
    destinationModalFooterHintText: { fontSize: 12, fontWeight: '700', color: '#64748B' },
    destinationFiltersWrap: {
        paddingHorizontal: 16,
        paddingBottom: 4,
    },
    modalFilterLabel: {
        fontSize: 11,
        fontWeight: '800',
        color: '#475569',
        marginBottom: 8,
        marginTop: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },
    modalFilterRow: { paddingBottom: 4, paddingRight: 8 },
    modalFilterRowWrap: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 2 },
    modalFilterChip: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#F8FAFC',
        marginRight: 8,
        marginBottom: 8,
    },
    modalFilterChipActive: { backgroundColor: '#E0F2FE', borderColor: '#0EA5E9' },
    modalFilterChipText: { fontSize: 12, fontWeight: '600', color: '#334155' },
    modalFilterChipTextActive: { color: '#0369A1', fontWeight: '800' },
    modalSearchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        paddingHorizontal: 10,
        marginTop: 2,
        marginBottom: 6,
    },
    modalSearchInput: {
        flex: 1,
        fontSize: 13,
        color: '#0F172A',
        paddingVertical: 10,
    },
    emptyModalContainer: { alignItems: 'center', paddingVertical: 30 },
    emptyModalText: { fontSize: 14, color: '#64748B', fontWeight: '600' },
    toastContainer: { position: 'absolute', top: 50, alignSelf: 'center', backgroundColor: '#1F2937', flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 12, width: '90%', shadowOpacity: 0.2, elevation: 5 },
    toastSuccess: { borderLeftWidth: 4, borderLeftColor: '#22C55E' },
    toastError: { borderLeftWidth: 4, borderLeftColor: '#EF4444' },
    toastText: { color: '#fff', marginLeft: 10, fontWeight: '600' }
});