import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#fff' },
    header: { position: 'relative', height: 120, justifyContent: 'center' },
    headerImage: { width: '100%', height: '100%', resizeMode: 'cover', borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    overlay: { ...StyleSheet.absoluteFillObject, borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    headerTitle: { position: 'absolute', bottom: 15, left: 20, color: '#fff', fontSize: 18, fontWeight: '700', letterSpacing: 1 },
    contentContainer: { padding: 16, paddingBottom: 30 },
    section: { marginBottom: 20 },
    sectionTitle: { fontSize: 14, fontWeight: '700', color: '#1A2332', marginBottom: 12 },
    cardHeader: { fontSize: 16, fontWeight: '700', color: '#1A2332', marginBottom: 10, textAlign: 'center' },
    priceCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#1A2332', borderRadius: 12, padding: 16, marginBottom: 20 },
    priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
    priceLabel: { fontSize: 13, color: '#1A2332', fontWeight: '500' },
    priceValue: { fontSize: 13, color: '#1A2332', fontWeight: '600' },
    priceDivider: { height: 1, backgroundColor: '#1A2332', marginVertical: 10 },
    totalLabel: { fontSize: 15, fontWeight: '700', color: '#1A2332' },
    totalValue: { fontSize: 15, fontWeight: '700', color: '#00A8FF' },
    paymentOption: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E0E6ED', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 12, backgroundColor: '#F5F7FA' },
    radioButton: { width: 20, height: 20, borderRadius: 10, borderWidth: 2, borderColor: '#1A2332', marginRight: 12, justifyContent: 'center', alignItems: 'center' },
    radioButtonActive: { borderColor: '#00A8FF' },
    radioButtonInner: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#00A8FF' },
    paymentOptionText: { fontSize: 13, color: '#1A2332', fontWeight: '500' },
    infoText: { fontSize: 12, color: '#8B98A8', marginTop: 8 },
    billingCardReview: { backgroundColor: '#F5F7FA', borderRadius: 8, padding: 12, borderWidth: 1, borderColor: '#E0E6ED' },
    billingRowReview: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
    billingLabelReview: { fontSize: 13, fontWeight: '500', color: '#8B98A8', width: '30%' },
    billingValueReview: { fontSize: 13, fontWeight: '600', color: '#1A2332', flex: 1, textAlign: 'right' },
    confirmButton: { backgroundColor: '#00A8FF', paddingVertical: 12, borderRadius: 8, alignItems: 'center', marginTop: 10 },
    confirmButtonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
});
