import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    listFooterLoader: {
        paddingVertical: 16,
        alignItems: 'center',
    },
    headerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    headerBackButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        backgroundColor: '#F8FAFC',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    headerHeadingWrap: {
        flex: 1,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
    },
    headerSubtitle: {
        marginTop: 2,
        color: '#64748B',
        fontSize: 12,
        fontWeight: '600',
    },
    searchWrap: {
        marginTop: 14,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 8,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8FAFC',
    },
    searchInput: {
        flex: 1,
        marginLeft: 8,
        fontSize: 14,
        color: '#0F172A',
    },
    filterRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 4,
    },
    filterChip: {
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 999,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: '#FFFFFF',
    },
    filterChipActive: {
        backgroundColor: '#DBEAFE',
        borderColor: '#93C5FD',
    },
    filterChipText: {
        color: '#64748B',
        fontSize: 12,
        fontWeight: '700',
    },
    filterChipTextActive: {
        color: '#1D4ED8',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    conversationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        backgroundColor: '#fff',
    },
    conversationUnread: {
        backgroundColor: '#F8FAFF',
    },
    avatar: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#00A8FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    avatarImage: {
        width: 50,
        height: 50,
        borderRadius: 25,
        marginRight: 15,
        backgroundColor: '#f0f0f0'
    },
    avatarText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    conversationName: {
        fontSize: 16,
        color: '#0F172A',
        fontWeight: '600',
    },
    conversationNameUnread: {
        fontWeight: '800',
    },
    metaWrap: {
        flex: 1,
    },
    topLine: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    topRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    timeText: {
        fontSize: 11,
        color: '#94A3B8',
        fontWeight: '600',
    },
    bottomLine: {
        marginTop: 3,
        flexDirection: 'row',
        alignItems: 'center',
    },
    previewText: {
        flex: 1,
        fontSize: 13,
        color: '#64748B',
    },
    unreadBadge: {
        minWidth: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: '#2563EB',
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 6,
        marginLeft: 8,
    },
    unreadBadgeText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: '800',
    },
    emptyText: {
        textAlign: 'center',
        fontSize: 16,
        color: '#888',
    },
    emptyWrap: {
        marginTop: 50,
        paddingHorizontal: 24,
        alignItems: 'center',
    },
    emptySubtext: {
        marginTop: 8,
        textAlign: 'center',
        fontSize: 13,
        color: '#64748B',
    },
    retryButton: {
        marginTop: 14,
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: '#2563EB',
    },
    retryButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '700',
    },
    menuOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.35)',
        justifyContent: 'flex-end',
        padding: 16,
    },
    menuCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 12,
    },
    menuTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#0F172A',
        marginBottom: 6,
        paddingHorizontal: 6,
    },
    menuAction: {
        paddingVertical: 12,
        paddingHorizontal: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F1F5F9',
    },
    menuActionText: {
        fontSize: 14,
        color: '#1E293B',
        fontWeight: '600',
    },
    menuActionDanger: {
        borderBottomWidth: 0,
    },
    menuActionTextDanger: {
        color: '#B91C1C',
    },
    undoBarWrap: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 14,
        paddingBottom: 8,
    },
    undoBar: {
        backgroundColor: '#0F172A',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    undoText: {
        color: '#E2E8F0',
        fontSize: 13,
        fontWeight: '600',
        flex: 1,
    },
    undoButton: {
        marginLeft: 12,
        paddingVertical: 4,
        paddingHorizontal: 8,
    },
    undoButtonText: {
        color: '#38BDF8',
        fontWeight: '800',
        fontSize: 13,
    },
});
