import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#F8FAFC' },
    loadingCenter: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: '#fff' },
    
    header: { height: 140, justifyContent: 'center' },
    headerImage: { width: '100%', height: '100%', resizeMode: 'cover', borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    overlay: { ...StyleSheet.absoluteFillObject, borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    headerTitle: { position: 'absolute', bottom: 35, left: 20, color: '#fff', fontSize: 20, fontWeight: '800' },
    headerSubtitle: { position: 'absolute', bottom: 15, left: 20, color: 'rgba(255,255,255,0.9)', fontSize: 14, fontWeight: '500' },
    
    backButton: { position: 'absolute', top: 20, left: 20, padding: 5, zIndex: 10 },

    emptyContainer: { flex: 1, justifyContent: "center", alignItems: "center", paddingVertical: 60, paddingHorizontal: 20 },
    emptyText: { fontSize: 16, color: '#8B98A8', textAlign: 'center' },

    filterCard: {
        marginHorizontal: 16,
        marginTop: 12,
        marginBottom: 4,
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 14,
        padding: 12,
    },
    searchInputWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 10,
        backgroundColor: '#F8FAFC',
        paddingHorizontal: 10,
        gap: 8,
    },
    searchInput: {
        flex: 1,
        paddingVertical: 10,
        fontSize: 13,
        color: '#0F172A',
    },
    filterChipRow: {
        paddingTop: 10,
        gap: 8,
    },
    filterChip: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 999,
        backgroundColor: '#F8FAFC',
    },
    filterChipActive: {
        backgroundColor: '#E0F2FE',
        borderColor: '#0EA5E9',
    },
    filterChipText: {
        fontSize: 12,
        color: '#475569',
        fontWeight: '600',
    },
    filterChipTextActive: {
        color: '#0369A1',
        fontWeight: '700',
    },
    ratingRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 10,
    },
    ratingPill: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#E0E6ED',
        backgroundColor: '#F5F7FA',
    },
    ratingPillActive: {
        backgroundColor: '#00A8FF',
        borderColor: '#00A8FF',
    },
    ratingPillText: {
        fontSize: 12,
        color: '#475569',
        fontWeight: '600',
    },
    ratingPillTextActive: {
        color: '#fff',
        fontWeight: '700',
    },
    clearFiltersButton: {
        marginTop: 10,
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: '#F0F9FF',
        borderWidth: 1,
        borderColor: '#BAE6FD',
    },
    clearFiltersText: {
        fontSize: 12,
        color: '#0369A1',
        fontWeight: '700',
    },

    contentContainer: { padding: 20 },
    sectionLabel: { fontSize: 14, fontWeight: '700', color: '#64748B', marginBottom: 15, textTransform: 'uppercase', letterSpacing: 0.5 },
    filteredEmptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 28,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 12,
        backgroundColor: '#F8FAFC',
        marginBottom: 14,
    },
    filteredEmptyText: {
        marginTop: 10,
        fontSize: 13,
        color: '#64748B',
        fontWeight: '600',
        textAlign: 'center',
    },

    destinationCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
        overflow: 'hidden',
    },
    imageContainer: { height: 160, width: '100%', position: 'relative' },
    cardImage: { width: '100%', height: '100%', resizeMode: 'cover' },
    cardGradient: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 80 },
    cardTextOverlay: { position: 'absolute', bottom: 12, left: 16, right: 16 },
    
    destinationName: { fontSize: 18, fontWeight: '700', color: '#fff', marginBottom: 4, textShadowColor: 'rgba(0,0,0,0.3)', textShadowRadius: 3 },
    locationRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    locationText: { fontSize: 12, color: 'rgba(255,255,255,0.9)', fontWeight: '500' },

    cardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 12, backgroundColor: '#fff' },
    metaBadgeRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    categoryBadge: { fontSize: 12, color: '#64748B', backgroundColor: '#F1F5F9', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, fontWeight: '600' },
    footerRatingBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, backgroundColor: '#FEF9C3' },
    footerRatingText: { fontSize: 11, fontWeight: '700', color: '#854D0E' },
    
    arrowBtn: { flexDirection: 'row', alignItems: 'center', gap: 6 },
    selectText: { fontSize: 13, color: '#00A8FF', fontWeight: '700' }
});
