import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "#fff" },
    container: { flex: 1, backgroundColor: "#fff" },
    simpleHeader: {
        height: 56,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
    },
    simpleBackButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        backgroundColor: '#F8FAFC',
        alignItems: 'center',
        justifyContent: 'center',
    },
    simpleHeaderTitle: {
        fontSize: 17,
        fontWeight: '700',
        color: '#0F172A',
    },
    simpleHeaderSpacer: {
        width: 34,
        height: 34,
    },
    header: { position: "relative", height: 120, justifyContent: "center" },
    headerImage: { width: "100%", height: "100%", resizeMode: "cover", borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    overlay: { ...StyleSheet.absoluteFillObject, borderBottomLeftRadius: 25, borderBottomRightRadius: 25 },
    headerBackButton: {
        position: 'absolute',
        top: 12,
        left: 14,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 3,
    },
    headerTitle: { position: "absolute", bottom: 15, left: 62, color: "#fff", fontSize: 18, fontWeight: "700", letterSpacing: 1 },
    guideInfo: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#fff", paddingVertical: 10, paddingHorizontal: 15, borderBottomWidth: 1, borderColor: "#ddd" },
    guideName: { fontSize: 14, fontWeight: "700", color: "#00051A" },
    headerAvatar: { width: 32, height: 32, borderRadius: 16, marginRight: 10, backgroundColor: '#eee' },
    headerAvatarPlaceholder: { width: 32, height: 32, borderRadius: 16, marginRight: 10, backgroundColor: '#00A8FF', alignItems: 'center', justifyContent: 'center' },
    headerAvatarText: { color: '#fff', fontWeight: 'bold', fontSize: 14 },
    messagesContainer: { flex: 1, padding: 15 },
    messageBox: { marginBottom: 25 },
    sentMessage: { alignItems: "flex-end" },
    receivedMessage: { alignItems: "flex-start" },
    senderName: { fontSize: 12, fontWeight: "600", color: "#555", marginBottom: 4, marginLeft: 10 },
    messageBubble: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 16, maxWidth: "75%" },
    sentBubble: { backgroundColor: "#00051A" },
    receivedBubble: { backgroundColor: "#E9EEF3" },
    messageText: { fontSize: 15 },
    sentText: { color: "#fff" },
    receivedText: { color: "#000" },
    timestamp: { fontSize: 11, color: "#999", marginTop: 4, marginHorizontal: 10 },
    statusRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4, marginHorizontal: 10, gap: 8 },
    statusText: { fontSize: 11, color: '#94A3B8', fontWeight: '600' },
    statusFailed: { color: '#DC2626' },
    retryBtn: { paddingHorizontal: 8, paddingVertical: 3, backgroundColor: '#FEE2E2', borderRadius: 999 },
    retryBtnText: { fontSize: 10, fontWeight: '700', color: '#B91C1C' },
    emptyThreadContainer: { alignItems: 'center', justifyContent: 'center', paddingVertical: 36, paddingHorizontal: 20 },
    emptyThreadTitle: { fontSize: 16, fontWeight: '700', color: '#1F2937', marginBottom: 6 },
    emptyThreadText: { fontSize: 13, color: '#6B7280', textAlign: 'center' },
    modalOverlay: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(0,0,0,0.4)" },
    modalContainer: { backgroundColor: "#fff", borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20 },
    modalTitle: { fontSize: 16, fontWeight: "700", color: "#00051A", textAlign: "center", marginBottom: 15 },
    reasonLabel: { fontWeight: "600", color: "#000", marginBottom: 8 },
    reasonOption: { borderWidth: 1, borderColor: "#ccc", borderRadius: 8, paddingVertical: 8, paddingHorizontal: 10, marginBottom: 8 },
    selectedReason: { borderColor: "#00051A", backgroundColor: "#E9EEF3" },
    reasonText: { color: "#333", fontSize: 14 },
    selectedReasonText: { color: "#00051A", fontWeight: "700" },
    reasonInput: { borderWidth: 1, borderColor: "#ccc", borderRadius: 8, padding: 10, height: 80, textAlignVertical: "top", marginBottom: 10 },
    modalButtons: { flexDirection: "row", justifyContent: "center", marginTop: 10 },
    modalButton: { borderRadius: 8, paddingVertical: 10, paddingHorizontal: 25, marginHorizontal: 10 },
    yesButton: { backgroundColor: "#00051A" },
    noButton: { backgroundColor: "#555" },
    buttonText: { color: "#fff", fontSize: 14, fontWeight: "600" },
    inputSafeArea: { backgroundColor: "#F0F0F0" },
    inputContainer: { flexDirection: "row", alignItems: "center", backgroundColor: "#F0F0F0", paddingVertical: 7, paddingHorizontal: 7 },
    iconButton: { paddingHorizontal: 6 },
    textInputWrapper: { flex: 1, marginHorizontal: 8, backgroundColor: '#fff', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8 },
    input: { fontSize: 15, maxHeight: 100 },
    sendButton: { backgroundColor: "#007AFF", borderRadius: 20, width: 36, height: 36, justifyContent: "center", alignItems: "center" },
    undoBarWrap: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        paddingHorizontal: 14,
        paddingBottom: 8,
    },
    undoBar: {
        backgroundColor: '#0F172A',
        borderRadius: 12,
        paddingVertical: 12,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    undoText: {
        color: '#E2E8F0',
        fontSize: 13,
        fontWeight: '600',
        flex: 1,
    },
    undoButton: {
        marginLeft: 12,
        paddingVertical: 4,
        paddingHorizontal: 8,
    },
    undoButtonText: {
        color: '#38BDF8',
        fontWeight: '800',
        fontSize: 13,
    },
    deleteActionOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.45)',
        justifyContent: 'flex-end',
        padding: 16,
    },
    deleteActionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        paddingVertical: 8,
    },
    deleteActionTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#0F172A',
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 6,
    },
    deleteActionButton: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#E2E8F0',
    },
    deleteActionText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1E293B',
    },
    deleteActionDangerText: {
        color: '#B91C1C',
    },
    deleteActionCancelText: {
        fontSize: 15,
        fontWeight: '700',
        color: '#334155',
    },
});
