import { StyleSheet } from "react-native";

const PRIMARY_COLOR = '#0072FF';
const SURFACE_COLOR = '#FFFFFF';
const TEXT_PRIMARY = '#1E293B';
const TEXT_SECONDARY = '#64748B';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    loaderFallback: { flex: 1, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center' },
    header: { height: 100, position: 'relative', marginBottom: 20 },
    headerImage: { width: '100%', height: '100%', borderBottomLeftRadius: 30, borderBottomRightRadius: 30 },
    overlay: { ...StyleSheet.absoluteFillObject, borderBottomLeftRadius: 30, borderBottomRightRadius: 30 },
    headerContent: { position: 'absolute', bottom: 15, left: 20, right: 20, flexDirection: 'row', alignItems: 'center' },
    backButton: { marginRight: 15, padding: 5 },
    headerTitle: { color: '#fff', fontSize: 20, fontWeight: '800', letterSpacing: 0.5 },
    contentContainer: { paddingHorizontal: 20 },
    card: { backgroundColor: SURFACE_COLOR, borderRadius: 16, padding: 16, marginBottom: 24, shadowColor: '#000', shadowOffset: {width:0, height:4}, shadowOpacity:0.05, shadowRadius:8, elevation:2 },
    guideHeader: { flexDirection: 'row', alignItems: 'center' },
    avatarContainer: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#1E293B', justifyContent: 'center', alignItems: 'center', marginRight: 16 },
    avatarHasImage: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E2E8F0', padding: 1 },
    avatarImage: { width: '100%', height: '100%', borderRadius: 28 },
    guideInfo: { flex: 1 },
    guideName: { fontSize: 18, fontWeight: '700', color: TEXT_PRIMARY },
    guideLocation: { fontSize: 13, color: '#8B98A8', marginTop: 2 },
    guideRatingRow: { flexDirection: 'row', alignItems: 'center', marginTop: 4 },
    guideRatingText: { fontSize: 13, color: '#C99700', marginLeft: 4, fontWeight: '600' },
    guideSub: { fontSize: 13, color: TEXT_SECONDARY },
    providerScheduleWrap: { marginTop: 8, gap: 2 },
    providerScheduleRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap' },
    providerScheduleLabel: { fontSize: 12, color: '#334155', fontWeight: '600', marginRight: 4 },
    providerScheduleValue: { fontSize: 12, color: '#0F172A', fontWeight: '700' },
    verifiedTag: { flexDirection: 'row', alignItems: 'center', marginTop: 4, gap: 4, backgroundColor: '#ECFDF5', alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
    verifiedText: { fontSize: 11, color: '#059669', fontWeight: '600' },
    sectionTitle: { fontSize: 16, fontWeight: '700', color: TEXT_PRIMARY, marginBottom: 12 },
    newPackageCallout: {
        marginBottom: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#BAE6FD',
        backgroundColor: '#E0F2FE',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    newPackageCalloutTitle: { fontSize: 12, fontWeight: '800', color: '#075985' },
    newPackageCalloutSubtext: { fontSize: 11, color: '#0369A1', marginTop: 2 },
    sectionHeaderWithAction: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10, marginBottom: 12 },
    viewStopsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: '#EFF6FF',
        borderWidth: 1,
        borderColor: '#BFDBFE',
    },
    viewStopsButtonText: { fontSize: 12, fontWeight: '700', color: '#1D4ED8' },
    viewAccommodationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
        gap: 6,
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: '#EFF6FF',
        borderWidth: 1,
        borderColor: '#BFDBFE',
        marginBottom: 8,
    },
    viewAccommodationButtonText: { fontSize: 12, fontWeight: '700', color: '#1D4ED8' },

    accommodationDetailsOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        justifyContent: 'flex-end',
    },
    accommodationDetailsSheet: {
        maxHeight: '88%',
        minHeight: '45%',
        backgroundColor: '#F8FAFC',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    accommodationDetailsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
    },
    accommodationDetailsTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: '#0F172A',
    },
    accommodationDetailsCloseButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E2E8F0',
    },
    accommodationDetailsContent: {
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 28,
    },
    accommodationDetailsHero: {
        width: '100%',
        height: 180,
        borderRadius: 12,
        backgroundColor: '#E2E8F0',
        marginBottom: 12,
    },
    accommodationDetailsName: {
        fontSize: 16,
        fontWeight: '800',
        color: '#0F172A',
    },
    accommodationDetailsMeta: {
        marginTop: 4,
        fontSize: 13,
        color: '#475569',
        fontWeight: '600',
    },
    accommodationDetailsRate: {
        marginTop: 8,
        fontSize: 13,
        color: '#0369A1',
        fontWeight: '800',
    },
    accommodationDetailsSection: {
        marginTop: 12,
    },
    accommodationDetailsSectionTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#1E293B',
        marginBottom: 8,
    },
    accommodationTransportCard: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#DDE5F0',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 10,
        paddingVertical: 9,
        marginBottom: 8,
    },
    accommodationTransportTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: '#0F172A',
    },
    accommodationTransportMeta: {
        marginTop: 3,
        fontSize: 12,
        color: '#475569',
        fontWeight: '600',
    },
    accommodationDetailsEmpty: {
        padding: 20,
        alignItems: 'center',
    },
    
    packageScroll: { flexDirection: 'row', marginBottom: 20 },
    packagePill: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, backgroundColor: '#F1F5F9', marginRight: 10, borderWidth: 1, borderColor: '#E2E8F0' },
    packagePillActive: { backgroundColor: '#EFF6FF', borderColor: PRIMARY_COLOR },
    packagePillText: { fontSize: 14, fontWeight: '600', color: TEXT_SECONDARY },
    packagePillTextActive: { color: PRIMARY_COLOR },
    accommodationSelectorCard: { backgroundColor: '#F5F7FA', borderRadius: 15, padding: 14, borderWidth: 1, borderColor: '#E0E6ED', marginBottom: 14 },
    readonlyAccommodationCard: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 14, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 14 },
    readonlyAccommodationRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    readonlyAccommodationName: { flex: 1, fontSize: 14, fontWeight: '700', color: TEXT_PRIMARY, marginRight: 10 },
    readonlyAccommodationPrice: { fontSize: 13, fontWeight: '700', color: '#0369A1' },
    sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 8 },
    detailsHeader: { fontSize: 16, fontWeight: '700', color: '#1A2332' },
    
    accScroll: { marginTop: 10, paddingBottom: 5 },
    accCard: { width: 140, marginRight: 12, backgroundColor: SURFACE_COLOR, borderRadius: 12, borderWidth: 2, borderColor: '#E2E8F0', overflow: 'hidden', position: 'relative', height: 110 },
    accCardActive: { borderColor: PRIMARY_COLOR },
    accImage: { width: '100%', height: '100%', position: 'absolute' },
    accOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, height: '60%', backgroundColor: 'rgba(0,0,0,0.5)' },
    accInfo: { position: 'absolute', bottom: 8, left: 8, right: 8 },
    accTitle: { fontSize: 13, fontWeight: '700', color: '#fff', textShadowColor: 'rgba(0,0,0,0.8)', textShadowRadius: 3 },
    accPrice: { fontSize: 11, color: '#E0F2FE', fontWeight: '700', marginTop: 2 },
    accCheck: { position: 'absolute', top: 8, right: 8, backgroundColor: PRIMARY_COLOR, borderRadius: 12, padding: 2 },

    seqDayLabel: { fontSize: 15, fontWeight: '800', color: PRIMARY_COLOR, marginBottom: 10 },
    timelineContainer: { marginTop: 10 },
    timelineItem: { flexDirection: 'row', marginBottom: 15 },
    timeColumn: { width: 85, alignItems: 'center', paddingRight: 10 },
    timeText: { fontSize: 12, fontWeight: '700', color: TEXT_PRIMARY },
    timeSubText: { fontSize: 10, color: TEXT_SECONDARY, marginTop: 2 },
    timeConnector: { flex: 1, width: 1, backgroundColor: '#E2E8F0', marginTop: 4 },
    
    activityCard: { flex: 1, backgroundColor: '#F8FAFC', borderRadius: 8, padding: 10, borderWidth: 1, borderColor: '#E2E8F0' },
    activityHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
    activityDot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
    activityTitle: { fontSize: 14, fontWeight: '700', color: TEXT_PRIMARY },
    
    typeBadge: { alignSelf: 'flex-start', backgroundColor: '#FFFFFF', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4, borderWidth: 1, borderColor: '#E2E8F0' },
    typeText: { fontSize: 10, color: TEXT_SECONDARY, fontWeight: '600' },
    
    datesRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
    oneDayTripCard: { marginBottom: 6 },
    oneDayNote: { fontSize: 12, color: '#64748B', marginBottom: 20, fontStyle: 'italic' },
    dateBox: { flex: 1, backgroundColor: SURFACE_COLOR, padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0' },
    dateLabel: { fontSize: 12, color: TEXT_SECONDARY, marginBottom: 4 },
    dateValueRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    dateValue: { fontSize: 14, fontWeight: '700', color: TEXT_PRIMARY },
    connector: { width: 10, height: 1, backgroundColor: '#CBD5E1', marginHorizontal: 10 },
    switchContainer: { flexDirection: 'row', backgroundColor: '#F1F5F9', borderRadius: 12, padding: 4, marginBottom: 16 },
    switchOption: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
    switchActive: { backgroundColor: PRIMARY_COLOR, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 2, elevation: 1 },
    switchText: { fontSize: 14, fontWeight: '600', color: TEXT_SECONDARY },
    switchTextActive: { color: '#FFFFFF', fontWeight: '700' },
    modernInput: { backgroundColor: SURFACE_COLOR, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 14, fontSize: 15, color: TEXT_PRIMARY, },
    inputRow: { flexDirection: 'row' },
    fieldErrorText: { color: '#DC2626', fontSize: 12, lineHeight: 16, marginTop: 6, marginBottom: 8, fontWeight: '600' },
    inputGroup: { marginBottom: 20 },
    inputLabel: { fontSize: 13, fontWeight: '600', color: TEXT_SECONDARY, marginBottom: 8 },
    
    guestNamesContainer: { marginTop: 15, paddingTop: 15, borderTopWidth: 1, borderTopColor: '#E2E8F0' },

    kycRow: { flexDirection: 'row', gap: 12 },
    kycItem: { flex: 1, alignItems: 'center' },
    kycCard: { width: '100%', height: 120, backgroundColor: '#F8FAFC', borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F0', borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
    kycCardDone: { borderStyle: 'solid', borderColor: '#22C55E' },
    kycPlaceholder: { alignItems: 'center', gap: 8 },
    kycText: { fontSize: 13, fontWeight: '600', color: TEXT_SECONDARY },
    kycImage: { width: '100%', height: '100%' },
    checkBubble: { position: 'absolute', top: 8, right: 8, backgroundColor: '#22C55E', borderRadius: 12, padding: 2 },
    kycItemLabel: { marginTop: 8, fontSize: 12, color: '#475569', fontWeight: '700' },
    paymentScroll: { flexDirection: 'row', marginBottom: 24 },
    paymentOption: { marginRight: 12, width: 80, height: 80, backgroundColor: SURFACE_COLOR, borderRadius: 16, borderWidth: 1, borderColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center', gap: 8 },
    paymentOptionActive: { borderColor: PRIMARY_COLOR, backgroundColor: '#EFF6FF' },
    paymentIconCircle: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#F1F5F9', justifyContent: 'center', alignItems: 'center' },
    paymentIconCircleActive: { backgroundColor: PRIMARY_COLOR },
    paymentText: { fontSize: 12, fontWeight: '600', color: TEXT_SECONDARY },
    paymentTextActive: { color: PRIMARY_COLOR },
    receiptCard: { backgroundColor: SURFACE_COLOR, borderRadius: 20, padding: 20, borderWidth: 1, borderColor: '#E2E8F0', borderStyle: 'dashed' },
    receiptHeader: { alignItems: 'center', marginBottom: 16 },
    receiptTitle: { fontSize: 14, fontWeight: '700', color: TEXT_SECONDARY, textTransform: 'uppercase', letterSpacing: 1 },
    receiptRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
    receiptLabel: { fontSize: 14, color: TEXT_SECONDARY },
    receiptValue: { fontSize: 14, fontWeight: '600', color: TEXT_PRIMARY },
    receiptSubRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6, paddingLeft: 20 },
    receiptSubLabel: { flex: 1, fontSize: 12, color: '#475569', marginRight: 10 },
    receiptSubValue: { fontSize: 12, fontWeight: '600', color: '#1E293B' },
    receiptTotal: { fontSize: 18, fontWeight: '800' },
    receiptDivider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 12 },
    receiptNote: { fontSize: 11, color: PRIMARY_COLOR, fontStyle: 'italic', textAlign: 'right' },
    
    bottomBar: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: SURFACE_COLOR, paddingHorizontal: 24, paddingVertical: 16, paddingBottom: 30, borderTopWidth: 1, borderTopColor: '#F1F5F9', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', shadowColor: '#000', shadowOffset: {width:0, height:-2}, shadowOpacity:0.05, shadowRadius:10, elevation:10 },
    bottomLabel: { fontSize: 12, color: TEXT_SECONDARY, fontWeight: '600' },
    bottomPrice: { fontSize: 20, color: TEXT_PRIMARY, fontWeight: '800' },
    payButton: { backgroundColor: PRIMARY_COLOR, flexDirection: 'row', paddingVertical: 14, paddingHorizontal: 24, borderRadius: 14, alignItems: 'center', gap: 8, shadowColor: PRIMARY_COLOR, shadowOffset: {width:0, height:4}, shadowOpacity:0.3, shadowRadius:8, elevation:4 },
    payButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
    calendarCard: { backgroundColor: SURFACE_COLOR, borderRadius: 24, padding: 20 },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    modalTitle: { fontSize: 18, fontWeight: '700', color: TEXT_PRIMARY },
    closeBtn: { padding: 4, backgroundColor: '#F1F5F9', borderRadius: 20 },
    errorOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
    errorCard: { width: '85%', backgroundColor: SURFACE_COLOR, borderRadius: 24, padding: 24, alignItems: 'center', elevation: 10 },
    errorIconBox: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#FEF2F2', justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
    errorTitle: { fontSize: 20, fontWeight: '800', color: TEXT_PRIMARY, marginBottom: 8 },
    errorMessage: { fontSize: 14, color: TEXT_SECONDARY, textAlign: 'center', lineHeight: 20, marginBottom: 24 },
    errorButton: { backgroundColor: '#EF4444', paddingVertical: 12, width: '100%', alignItems: 'center', borderRadius: 12 },
    errorButtonText: { color: '#fff', fontWeight: '700', fontSize: 15 },

    assignedGuideCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F8FAFC', padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 8 },
    assignedGuideAvatar: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#E2E8F0', justifyContent: 'center', alignItems: 'center', marginRight: 12, overflow: 'hidden' },
    guideAvatarImage: { width: '100%', height: '100%' },
    assignedGuideName: { fontSize: 14, fontWeight: '700', color: TEXT_PRIMARY },
    assignedGuideRole: { fontSize: 12, color: '#0072FF', fontWeight: '600', marginTop: 2 },
    
    meetupCard: { backgroundColor: '#EFF6FF', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#BFDBFE', marginBottom: 8 },
    meetupRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12, paddingBottom: 12, borderBottomWidth: 1, borderBottomColor: '#D1E8FF' },
    meetupIconBox: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    meetupLabel: { fontSize: 11, color: '#60A5FA', fontWeight: '700', textTransform: 'uppercase', marginBottom: 2 },
    meetupValue: { fontSize: 14, color: '#1E3A8A', fontWeight: '600' },

    viewManifestButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#EFF6FF', paddingVertical: 14, borderRadius: 12, borderWidth: 1, borderColor: '#BFDBFE', marginBottom: 20 },
    viewManifestButtonText: { color: PRIMARY_COLOR, fontSize: 14, fontWeight: '700', marginLeft: 8 },
    manifestModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
    manifestModalContainer: { backgroundColor: SURFACE_COLOR, borderTopLeftRadius: 24, borderTopRightRadius: 24, height: '70%', padding: 20 },
    manifestModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    manifestModalTitle: { fontSize: 18, fontWeight: '800', color: TEXT_PRIMARY },

    manifestCard: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 12 },
    manifestHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    manifestGuest: { flex: 1, fontSize: 15, fontWeight: '700', color: '#1E293B', marginLeft: 8 },
    manifestPaxBadge: { backgroundColor: '#DBEAFE', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
    manifestPaxText: { color: '#1D4ED8', fontWeight: '800', fontSize: 12 },
    manifestRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 },
    manifestLabel: { fontSize: 13, color: '#64748B', width: 60 },
    manifestValue: { fontSize: 13, color: '#1E293B', fontWeight: '600', flex: 1, textAlign: 'right' },
    emptyManifest: { padding: 30, backgroundColor: '#F8FAFC', borderRadius: 16, alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0', borderStyle: 'dashed', marginTop: 20 },
    emptyManifestText: { color: '#64748B', fontStyle: 'italic', marginTop: 10, fontSize: 13 },
});