import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    loadingScreen: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F8FAFC',
    },
    loadingText: {
        marginTop: 10,
        color: '#475569',
        fontWeight: '600',
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 10,
    },
    backButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: '#E2E8F0',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: '#0F172A',
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#64748B',
        marginTop: 2,
        fontWeight: '600',
    },
    content: {
        paddingHorizontal: 16,
        paddingBottom: 90,
        gap: 12,
    },
    infoCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        padding: 14,
    },
    infoLabel: {
        fontSize: 11,
        textTransform: 'uppercase',
        fontWeight: '800',
        color: '#64748B',
        marginBottom: 4,
    },
    infoValue: {
        fontSize: 14,
        color: '#0F172A',
        fontWeight: '700',
        marginBottom: 10,
    },
    infoValueAmount: {
        fontSize: 16,
        color: '#0F766E',
        fontWeight: '800',
    },
    latestCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#BFDBFE',
        padding: 14,
    },
    latestTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    latestTitle: {
        fontSize: 13,
        color: '#1E3A8A',
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    latestMeta: {
        fontSize: 12,
        color: '#334155',
        marginBottom: 4,
        fontWeight: '600',
    },
    latestNotes: {
        marginTop: 6,
        fontSize: 12,
        color: '#0F172A',
        fontWeight: '700',
    },
    attachmentWrap: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#DBEAFE',
    },
    attachmentTitle: {
        fontSize: 11,
        fontWeight: '800',
        color: '#1E3A8A',
        textTransform: 'uppercase',
        marginBottom: 6,
    },
    attachmentPreview: {
        width: '100%',
        height: 170,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#E2E8F0',
    },
    attachmentPlaceholder: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#F1F5F9',
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    attachmentPlaceholderText: {
        marginLeft: 6,
        fontSize: 12,
        color: '#334155',
        fontWeight: '700',
    },
    attachmentButton: {
        marginTop: 8,
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#CCFBF1',
        borderWidth: 1,
        borderColor: '#99F6E4',
        flexDirection: 'row',
        alignItems: 'center',
    },
    attachmentButtonText: {
        color: '#0F766E',
        fontSize: 12,
        fontWeight: '800',
    },
    sectionCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        padding: 14,
    },
    sectionTitle: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '800',
        marginBottom: 4,
        textTransform: 'uppercase',
    },
    sectionHint: {
        fontSize: 12,
        color: '#64748B',
        marginBottom: 10,
    },
    policyCard: {
        backgroundColor: '#ECFEFF',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#A5F3FC',
        padding: 12,
    },
    policyCardWarning: {
        backgroundColor: '#FFFBEB',
        borderColor: '#FCD34D',
    },
    policyHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    policyTitle: {
        marginLeft: 6,
        fontSize: 12,
        fontWeight: '800',
        color: '#0F766E',
        textTransform: 'uppercase',
    },
    policyTitleWarning: {
        color: '#B45309',
    },
    policyText: {
        fontSize: 12,
        color: '#134E4A',
        fontWeight: '600',
    },
    policyTextWarning: {
        color: '#92400E',
    },
    policyMetaText: {
        marginTop: 4,
        fontSize: 11,
        color: '#0F766E',
        fontWeight: '700',
    },
    policyMetaTextWarning: {
        color: '#B45309',
    },
    fieldLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#334155',
        marginBottom: 6,
        marginTop: 6,
    },
    reasonInput: {
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 10,
        minHeight: 98,
        textAlignVertical: 'top',
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: '#0F172A',
        fontSize: 13,
        backgroundColor: '#F8FAFC',
    },
    uploadButton: {
        marginTop: 2,
        backgroundColor: '#CCFBF1',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#99F6E4',
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
        alignSelf: 'flex-start',
    },
    uploadButtonText: {
        fontSize: 12,
        fontWeight: '800',
        color: '#0F766E',
    },
    proofPreviewWrap: {
        marginTop: 10,
        alignItems: 'flex-start',
    },
    proofPreview: {
        width: 120,
        height: 120,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        backgroundColor: '#E2E8F0',
    },
    proofName: {
        marginTop: 6,
        fontSize: 11,
        color: '#475569',
        maxWidth: 200,
        fontWeight: '600',
    },
    warningBox: {
        marginTop: 12,
        backgroundColor: '#FEF3C7',
        borderWidth: 1,
        borderColor: '#FCD34D',
        borderRadius: 10,
        padding: 10,
        flexDirection: 'row',
        alignItems: 'flex-start',
    },
    warningText: {
        flex: 1,
        marginLeft: 8,
        fontSize: 12,
        color: '#92400E',
        fontWeight: '700',
    },
    submitButton: {
        marginTop: 12,
        backgroundColor: '#0EA5E9',
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
    },
    submitButtonText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '800',
    },
    disabledButton: {
        opacity: 0.55,
    },
    emptyHistoryText: {
        marginTop: 6,
        color: '#64748B',
        fontSize: 12,
        fontWeight: '600',
    },
    historyCard: {
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 10,
        padding: 10,
        marginTop: 8,
        backgroundColor: '#F8FAFC',
    },
    historyTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    historyId: {
        fontSize: 12,
        fontWeight: '800',
        color: '#0F172A',
    },
    historyText: {
        fontSize: 12,
        color: '#334155',
        marginBottom: 2,
        fontWeight: '600',
    },
    historyNotes: {
        marginTop: 4,
        fontSize: 12,
        color: '#1E293B',
        fontWeight: '700',
    },
    historyAttachmentButton: {
        marginTop: 8,
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        paddingVertical: 7,
        borderRadius: 8,
        backgroundColor: '#ECFEFF',
        borderWidth: 1,
        borderColor: '#A5F3FC',
    },
    historyAttachmentText: {
        color: '#0F766E',
        fontSize: 11,
        fontWeight: '800',
    },
    statusChip: {
        borderRadius: 999,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    statusChipText: {
        fontSize: 10,
        textTransform: 'uppercase',
        fontWeight: '800',
    },
    toast: {
        position: 'absolute',
        left: 16,
        right: 16,
        bottom: 20,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
    },
    toastSuccess: {
        backgroundColor: '#16A34A',
    },
    toastError: {
        backgroundColor: '#DC2626',
    },
    toastText: {
        marginLeft: 8,
        color: '#FFFFFF',
        fontWeight: '700',
        fontSize: 12,
    },
});