import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    centeredView: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0, 0, 0, 0.6)' },
    modalView: { backgroundColor: 'white', borderTopLeftRadius: 25, borderTopRightRadius: 25, height: '90%', width: '100%', overflow: 'hidden' },
    imageContainer: { height: 200, width: '100%', position: 'relative' },
    heroImage: { width: '100%', height: '100%' },
    placeholderImage: { backgroundColor: '#ccc', justifyContent: 'center', alignItems: 'center' },
    closeButton: { position: 'absolute', top: 15, right: 15, zIndex: 10 },
    closeButtonBlur: { backgroundColor: 'rgba(255,255,255,0.8)', borderRadius: 20, padding: 8 },
    statusBadge: { position: 'absolute', bottom: 15, left: 20, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
    statusText: { color: 'white', fontWeight: 'bold', fontSize: 12, textTransform: 'uppercase' },
    
    contentContainer: { padding: 20 },
    title: { fontSize: 22, fontWeight: '800', color: '#1F2937', marginBottom: 2 },
    bookingId: { fontSize: 12, color: '#9CA3AF', marginBottom: 10 },
    divider: { height: 1, backgroundColor: '#F3F4F6', marginVertical: 20 },
    
    section: { marginBottom: 15 },
    sectionHeader: { fontSize: 14, fontWeight: '700', color: '#6B7280', textTransform: 'uppercase', marginBottom: 10, letterSpacing: 0.5 },
    sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 10, flexWrap: 'wrap' },
    viewStopDetailsButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#EFF6FF',
        borderWidth: 1,
        borderColor: '#BFDBFE',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    viewStopDetailsText: { fontSize: 11, fontWeight: '700', color: '#1D4ED8' },
    trackJourneyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#1D4ED8',
        borderWidth: 1,
        borderColor: '#1D4ED8',
        borderRadius: 999,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    trackJourneyText: { fontSize: 11, fontWeight: '700', color: '#FFFFFF' },
    
    providerRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F9FAFB', padding: 12, borderRadius: 12 },
    avatarImage: { width: 40, height: 40, borderRadius: 20, marginRight: 12, resizeMode: 'cover' },
    avatarPlaceholder: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#00A8FF', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    avatarText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
    providerName: { fontSize: 16, fontWeight: '600', color: '#1F2937' },
    providerRole: { fontSize: 12, color: '#6B7280' },

    manifestCardOverview: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: '#E2E8F0' },
    manifestHeaderTitle: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, gap: 8 },
    manifestHeaderText: { fontSize: 14, fontWeight: '800', color: '#1E3A8A', textTransform: 'uppercase' },
    manifestRowDetail: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    manifestLabelDetail: { fontSize: 13, color: '#64748B', fontWeight: '500' },
    manifestValueDetail: { fontSize: 13, color: '#0F172A', fontWeight: '700' },
    accommodationTransportCard: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#DDE5F0',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 10,
        paddingVertical: 8,
        marginBottom: 8,
    },
    accommodationTransportTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: '#0F172A',
    },
    accommodationTransportMeta: {
        marginTop: 2,
        fontSize: 12,
        color: '#475569',
        fontWeight: '600',
    },
    itineraryDayBlock: {
        backgroundColor: '#F8FAFC',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        marginBottom: 10,
    },
    itineraryDayTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#1D4ED8',
        marginBottom: 8,
    },
    itineraryStopItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 8,
        gap: 8,
    },
    itineraryStopDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#3B82F6',
        marginTop: 6,
    },
    itineraryStopName: {
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '700',
    },
    itineraryStopMeta: {
        marginTop: 2,
        fontSize: 12,
        color: '#64748B',
        fontWeight: '500',
    },
    itineraryEmptyBox: {
        backgroundColor: '#F8FAFC',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        padding: 12,
    },
    itineraryEmptyText: {
        fontSize: 12,
        color: '#64748B',
        fontWeight: '600',
    },
    manifestDivider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 12, borderStyle: 'dashed', borderWidth: 1, borderColor: '#CBD5E1' },

    priceSection: { marginTop: 0 },
    
    summaryCard: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 10 },
    summaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    summaryLabel: { fontSize: 14, color: '#475569', fontWeight: '500' },
    summaryValue: { fontSize: 15, color: '#0F172A', fontWeight: '700' },
    summarySubRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6, paddingLeft: 2 },
    summarySubLabel: { flex: 1, marginRight: 10, fontSize: 12, color: '#64748B', fontWeight: '500' },
    summarySubValue: { fontSize: 12, color: '#1E293B', fontWeight: '600' },
    summaryDate: { fontSize: 11, color: '#94A3B8', marginTop: 2 },
    summaryDivider: { height: 1, backgroundColor: '#E2E8F0', marginVertical: 8 },
    
    balanceHighlight: { marginTop: 8, padding: 12, borderRadius: 8, borderWidth: 1 },
    balanceHighlightRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    balanceHighlightLabel: { fontSize: 16, fontWeight: '800' },
    balanceHighlightValue: { fontSize: 18, fontWeight: '800' },
    balanceNote: { fontSize: 11, marginTop: 6, fontStyle: 'italic' },

    manifestCard: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 16, borderWidth: 1, borderColor: '#E2E8F0', marginBottom: 12 },
    manifestHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    manifestGuest: { flex: 1, fontSize: 15, fontWeight: '700', color: '#1E293B', marginLeft: 8 },
    manifestPaxBadge: { backgroundColor: '#DBEAFE', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 20 },
    manifestPaxText: { color: '#1D4ED8', fontWeight: '800', fontSize: 12 },
    manifestRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 },
    manifestLabel: { fontSize: 13, color: '#64748B', width: 60 },
    manifestValue: { fontSize: 13, color: '#1E293B', fontWeight: '600', flex: 1, textAlign: 'right' },
    emptyManifest: { padding: 30, backgroundColor: '#F8FAFC', borderRadius: 16, alignItems: 'center', borderWidth: 1, borderColor: '#E2E8F0', borderStyle: 'dashed', marginTop: 20 },
    emptyManifestText: { color: '#64748B', fontStyle: 'italic', marginTop: 10, fontSize: 13 },
});
