import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        justifyContent: 'flex-end',
        backgroundColor: 'rgba(15, 23, 42, 0.5)',
    },
    sheet: {
        backgroundColor: '#F8FAFC',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        maxHeight: '90%',
        minHeight: '52%',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: '#0F172A',
    },
    headerSubtitle: {
        marginTop: 2,
        fontSize: 12,
        fontWeight: '600',
        color: '#64748B',
    },
    closeButton: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#E2E8F0',
    },
    loadingWrap: {
        flex: 1,
        minHeight: 220,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    loadingText: {
        fontSize: 13,
        color: '#475569',
        fontWeight: '600',
    },
    content: {
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 24,
    },
    errorCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#FEE2E2',
        borderWidth: 1,
        borderColor: '#FCA5A5',
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 10,
        marginBottom: 10,
    },
    errorText: {
        flex: 1,
        fontSize: 12,
        color: '#7F1D1D',
        fontWeight: '600',
    },
    emptyBox: {
        marginTop: 10,
        borderRadius: 12,
        borderWidth: 1,
        borderStyle: 'dashed',
        borderColor: '#CBD5E1',
        backgroundColor: '#FFFFFF',
        alignItems: 'center',
        paddingVertical: 28,
        paddingHorizontal: 16,
    },
    emptyText: {
        marginTop: 8,
        fontSize: 13,
        color: '#64748B',
        fontWeight: '600',
        textAlign: 'center',
    },
    dayBlock: {
        marginBottom: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#DDE5F0',
        backgroundColor: '#FFFFFF',
        padding: 12,
    },
    dayTitle: {
        fontSize: 14,
        fontWeight: '800',
        color: '#1D4ED8',
        marginBottom: 10,
    },
    stopCard: {
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        backgroundColor: '#F8FAFC',
        padding: 10,
        marginBottom: 10,
    },
    stopHeaderRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
    },
    checkboxTapArea: {
        marginTop: 1,
        paddingRight: 2,
    },
    stopName: {
        fontSize: 14,
        fontWeight: '800',
        color: '#0F172A',
    },
    stopMeta: {
        marginTop: 2,
        fontSize: 12,
        fontWeight: '600',
        color: '#64748B',
    },
    checkStatusText: {
        marginTop: 6,
        marginBottom: 8,
        fontSize: 12,
        fontWeight: '700',
        color: '#334155',
    },
    remarksBlock: {
        marginTop: 2,
        marginBottom: 8,
    },
    remarksLabel: {
        fontSize: 12,
        color: '#475569',
        fontWeight: '700',
        marginBottom: 6,
    },
    remarksInput: {
        minHeight: 70,
        borderWidth: 1,
        borderColor: '#CBD5E1',
        borderRadius: 8,
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 10,
        paddingVertical: 8,
        fontSize: 13,
        color: '#0F172A',
        fontWeight: '500',
    },
    remarksInputReadOnly: {
        backgroundColor: '#F1F5F9',
        color: '#475569',
    },
    saveRemarkButton: {
        alignSelf: 'flex-start',
        marginTop: 8,
        paddingHorizontal: 14,
        paddingVertical: 7,
        borderRadius: 999,
        backgroundColor: '#1D4ED8',
    },
    saveRemarkButtonDisabled: {
        backgroundColor: '#93C5FD',
    },
    saveRemarkButtonText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '800',
    },
});

